### PR TITLE
Update requirements

### LINKED ISSUE #9: installing the package via pip fails in python 2.7 environment
The following command fails:
`docker run -it -v $(pwd):$(pwd) -w $(pwd) python:2.7 pip install -e .`
although it works fine with `python:3.7`:
`docker run -it -v $(pwd):$(pwd) -w $(pwd) python:3.7 pip install -e .`

### LINKED ISSUE #10: change corresponding author
The following is out of date:
https://github.com/plotly/dash-enterprise-auth/blob/dbea2f90e47a9666bb1386892c5a929968ed0304/setup.cfg#L4-L5

### PR DESCRIPTION
**Pull request by wbrgss**
These removed requirements should be already included via Dash's `setup.py` via [requires-install.txt](https://github.com/plotly/dash/blob/dev/requires-install.txt)

The `setup.cfg` was also updated to reflect those changes.

- Closes #10 with https://github.com/plotly/dash-enterprise-auth/pull/8/commits/2bb2d65f375f827660e97b1fb26fdea580b07d53
- Closes #9 https://github.com/plotly/dash-enterprise-auth/pull/8/commits/9b5b86a43d9087d3a94890b8307c635b0618ab7a

### CODE REVIEW

**Comment by wbrgss** [comment]
@antoinerg kind of a long shot but I wonder if the first line of `requirements.txt` (`dash-core-components>=0.40.0`) is messing up your aforementioned Python 2.7 Snapshots docker install somehow

**Comment by antoinerg** [comment]
@wbrgss You were on the right track. Do you mind if I push an extra commit here?

**Comment by wbrgss** [comment]
@antoinerg be my guest!

**Comment by antoinerg** [comment]
With https://github.com/plotly/dash-enterprise-auth/pull/8/commits/9b5b86a43d9087d3a94890b8307c635b0618ab7a the following command `docker run -it -v $(pwd):$(pwd) -w $(pwd) python:2.7 pip install -e .` now suceeds :tada:

**Comment by antoinerg** [comment]
This is ready for review @chriddyp @alexcjohnson !

**Comment by chriddyp** [comment]
💃

**Pull request merged**
