### PR TITLE
get token from callback_context

### PR DESCRIPTION
**Pull request by T4rk1n**
Take the token from the callback_context added in https://github.com/plotly/dash/pull/3051
Fix `get_username` called inside a background callback.

### CODE REVIEW

**Review by michaelbabyn — APPROVED** [review]
This looks good to me :woman_dancing:

**Comment by T4rk1n** [comment]
I changed to have the token from the request cookies first since this is also called from other routes. Also moved the flask context check to allow the function to be called from celery. Fix https://github.com/plotly/dekn/issues/8953

@michaelbabyn Can you have a look again? Thank you.

**Review by michaelbabyn — APPROVED** [review]
This works after the change to dash that I mentioned in https://github.com/plotly/dash/pull/3051 :woman_dancing:

**Review by HammadTheOne — APPROVED** [review]

**Comment by ndrezn** [comment]
@T4rk1n is this good to merge?

**Comment by T4rk1n** [comment]
> @T4rk1n is this good to merge?

Yes, just need to test it works with the latest dash version.

**Comment by T4rk1n** [comment]
Tested and working on de5

**Pull request merged**
